# Day 5

## Part 1

In [189]:
import re
import pandas as pd

In [190]:
# Import the input file into a DataFrame
vent_list = []
with open("inputs/day5.txt") as input_file:
    vent_list = pd.DataFrame([list(map(int, re.findall(r"[0-9]+", x))) for x in input_file.read().splitlines()], columns=["x1", "y1", "x2", "y2"])

vent_list.head()

    x1   y1   x2   y2
0  445  187  912  654
1  820   46   25  841
2  216  621  458  379
3  955  898   67   10
4  549  572  549  520

In [191]:
# Find max value for x and y
max_x, max_y = vent_list[["x1", "x2"]].max().max() +1, vent_list[["y1", "y2"]].max().max() +1
print(max_x, max_y)
    
# Create the diagram table
vent_diagram = pd.DataFrame([[0 for x in range(max_x)] for y in range(max_y)])
vent_diagram.head(10)

990 990

,0,1,2,3,4,5,6,7,8,9,...,980,981,982,983,984,985,986,987,988,989
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [192]:
# Apply lines to diagram
for index, row in vent_list[vent_list["x1"] == vent_list["x2"]].iterrows():
    for y in range(row[["y1", "y2"]].min(), row[["y1", "y2"]].max()+1):
        vent_diagram[row["x1"]][y] += 1

for index, row in vent_list[vent_list["y1"] == vent_list["y2"]].iterrows():
    for x in range(row[["x1", "x2"]].min(), row[["x1", "x2"]].max()+1):
        vent_diagram[x][row["y1"]] += 1

vent_diagram.head(10)

,0,1,2,3,4,5,6,7,8,9,...,980,981,982,983,984,985,986,987,988,989
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [193]:
# Calculate the number of overlaps
number_of_overlap = 0
for i in range(max_x):
    number_of_overlap += vent_diagram.loc[i][vent_diagram.loc[i] >= 2].count()

print(number_of_overlap)

5197

## Part 2

In [194]:
for index, row in vent_list[(vent_list["x1"] != vent_list["x2"]) & (vent_list["y1"] != vent_list["y2"])].iterrows():  
    if row["y1"] < row["y2"]:
        start_x, stop_x = row["x1"], row["x2"]
        start_y , stop_y = row["y1"], row["y2"]
    else:
        start_x, stop_x = row["x2"], row["x1"]
        start_y , stop_y = row["y2"], row["y1"]
    if start_x < stop_x:
        step = 1
    else:
        step = -1
    for i in range(stop_y - start_y +1):
        vent_diagram[start_x+i*step][start_y+i] += 1
vent_diagram.head(10)

,0,1,2,3,4,5,6,7,8,9,...,980,981,982,983,984,985,986,987,988,989
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [195]:
# Calculate the number of overlaps
number_of_overlap = 0
for i in range(max_x):
    number_of_overlap += vent_diagram.loc[i][vent_diagram.loc[i] >= 2].count()

print(number_of_overlap)

18605